#!/bin/sh
# Copyright Robert Zak
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Create a copy of the .prototxt file generated by caffe conversion

cp ct/yolov3.prototxt ct/yolov3_quant.prototxt

# Change the header

sed -i '2 s@input: "data"@#input: "data"@' ct/yolov3_quant.prototxt
sed -i '3 s@input_dim: 1@#input_dim: 1@'   ct/yolov3_quant.prototxt
sed -i '4 s@input_dim: 3@#input_dim: 3@'   ct/yolov3_quant.prototxt
sed -i '5 s@input_dim: 416@#input_dim: 416@' ct/yolov3_quant.prototxt
sed -i '6 s@input_dim: 416@#input_dim: 416@' ct/yolov3_quant.prototxt

# Add new content

sed -i '7 i \## Changes inserted by 2-prototxt-to-quant.sh script' ct/yolov3_quant.prototxt
sed -i '8 i \layer {' ct/yolov3_quant.prototxt
sed -i '9 i \  name: "data"' ct/yolov3_quant.prototxt
sed -i '10 i \  type: "ImageData"' ct/yolov3_quant.prototxt
sed -i '11 i \  top: "data"'  ct/yolov3_quant.prototxt
sed -i '12 i \  top: "label"' ct/yolov3_quant.prototxt
sed -i '13 i \  include {'    ct/yolov3_quant.prototxt
sed -i '14 i \    phase: TRAIN' ct/yolov3_quant.prototxt
sed -i '15 i \  }' ct/yolov3_quant.prototxt
sed -i '16 i \  transform_param {' ct/yolov3_quant.prototxt
sed -i '17 i \    mirror: false' ct/yolov3_quant.prototxt
sed -i '18 i \    yolo_height:416' ct/yolov3_quant.prototxt
sed -i '19 i \    yolo_width:416' ct/yolov3_quant.prototxt
sed -i '20 i \  }' ct/yolov3_quant.prototxt
sed -i '21 i \  image_data_param {' ct/yolov3_quant.prototxt
sed -i '22 i \    source: \"ct/calib.txt\"' ct/yolov3_quant.prototxt
sed -i '23 i \    root_folder: \"images\/\"' ct/yolov3_quant.prototxt
sed -i '24 i \' ct/yolov3_quant.prototxt
sed -i '25 i \    batch_size: 1' ct/yolov3_quant.prototxt
sed -i '26 i \    shuffle: false' ct/yolov3_quant.prototxt
sed -i '27 i \  }' ct/yolov3_quant.prototxt
sed -i '28 i \}' ct/yolov3_quant.prototxt
sed -i '29 i \## End of modifications by 2-prototxt-to-quant.sh script' ct/yolov3_quant.prototxt


